### ISSUE TITLE
Create DB schema

### ISSUE THREAD

**Issue by onema** [sdphp/grouptopics.org#14]
Users
Authentications
Groups
Votes
...

**Comment by cryptiklemur** [comment]
When this gets finished, can we have the schema file in `app/database/schema.sql`?

**Comment by johncongdon** [comment]
Just as a complete file?  I don't see why not, but that shouldn't be used for any of the database stuff.  Should all be done through migrations, right?

**Comment by cryptiklemur** [comment]
yeah, just nice to have a visual (albiet textual) representation of the schema
