### ISSUE TITLE
Need to change the naming convention of "ideas" to "topics" 

### ISSUE THREAD

**Issue by ericvanjohnson** [sdphp/grouptopics.org#40]
For some reason, and I am not going to name names (ME), someone (Again, me) created the default tables to reference the topics as "ideas" this is going to get confusing so we need to rename those tables and associations to read topic or topics and not idea or ideas.

**Comment by Kindari** [comment]
I'll address this tonight.

**Comment by Kindari** [comment]
Addressed in #42
