### ISSUE TITLE
[Approved] Switch to twig template engine

### ISSUE THREAD

**Issue by jasonmccallister** [sdphp/grouptopics.org#66]
Can we move from Blade to Twig? Any opposition?

**Comment by cryptiklemur** [comment]
I'm for this, personally dont like blade

**Comment by jasonmccallister** [comment]
I think blade has _some_ potential. However, the documentation is lacking in comparison to Twig.

**Comment by jasonmccallister** [comment]
As soon as I hear input from @shocm or @johncongdon I'm going to locally switch to Twig... 

Templates in Blade suck trying to set a variable in Blade (http://stackoverflow.com/questions/13002626/laravels-blade-how-can-i-set-variables-in-a-template) as opposed to Twig (http://twig.sensiolabs.org/doc/tags/set.html).

@aequasi unless the reigns have been relinquished to you ;)

**Comment by ericvanjohnson** [comment]
@themccallister I am fine switching template engines at this stage. Go for it.

**Comment by jasonmccallister** [comment]
I switched, ran into issues with Twig and Form::open. Moved back to Blade. PFY and kalen gave me a good run down on Blade. 

Only wish it was documented a little more thoroughly on their site.
