### ISSUE TITLE
Grouptopics Organization

### ISSUE THREAD

**Issue by jasonmccallister** [sdphp/grouptopics.org#69]
I was trying to wrap my head around the namespacing and organization of the domain this morning. I mocked up the following based on what I have seen and read on Laravel and basic software design.

This is what I came up with:
- `Grouptopics\Accounts`
  - `\Login.php`
  - `\Signup.php`
- `Grouptopics\Exceptions`
  - `\AccountActivated.php`
  - `\EmailExists.php`
  - `\UsernameExists.php`
- `Grouptopics\Notifications`
  - `\AccountSignup.php`
- `Grouptopics\Presentations`
  - `\NewPresentation.php`
- `Grouptopics\Validators`
  - `\Login.php`
  - `\Presentation.php`
  - `\Signup.php`
  - `\Topic.php`

Thoughts?

**Comment by cryptiklemur** [comment]
What is in `Grouptopics\Accounts\Login.php`? and `Singup.php`? 

You should drag the controllers into this directory too:
- Grouptopics
  - Controller
    - SecurityController - Login/Register/Logout Actions
    - IndexController - Main Dashboard Page
    - Other Controllers, in the ****Controller format
  - Validator
    - LoginValidator
    - Other validators, in the ****Validator format
  - Exception
    - AccountInactiveException
    - Other exceptions, in the ****Exception format
  - Security
    - UserProvider - Class that fetches the user from the database
    - UserAuthenticator - Authenticates the User
  - Model
    - User
    - Presentation
    - Group
  - Command
    - Any Commands, in the ****Command format

Thats what i would probably have the layout be.

To be honest, the `app/` directory structure is very strange to me... I've normally stored application code in `src/` and had the application configuration in `app/`. I prefer this, but, it may not be the "Laravel Way"

**Comment by jasonmccallister** [comment]
The actual logic to perform the login action, Abstracting it away from the controller.

**Comment by jasonmccallister** [comment]
Sorry, didn't see all of that I'll work that into it soon

**Comment by cryptiklemur** [comment]
@themccallister Updated the tree, to add `Security`

**Comment by jasonmccallister** [comment]
Out of curiosity, why singular named directories if they will contain multiple exceptions and etc?

**Comment by cryptiklemur** [comment]
Something I've picked up from the [Symfony framework](https://github.com/symfony/symfony/tree/master/src/Symfony/Bundle/FrameworkBundle). There are a couple situations where that isn't followed, but i try and follow it as much as possible. It makes the namespace make more sense, IMO. 

When you look at the Security controller, its `GroupTopics\Controller\SecurityController`, it kinda shows that its in the `Controller` namespace, instead of the "Controllers" directory.

**Comment by jasonmccallister** [comment]
Ah, excellent point. Makes a lot more sense now. It's a collection of files but you reference one object through the namespace.

Thank you, I'm learning a lot from you!
